import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./css/globals.css"
import "@mantine/carousel/styles.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children,
  styles = ""
}: Readonly<{
  children: React.ReactNode
  styles?: string
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${styles}`}
      >
        {children}
      </body>
    </html>
  )
}
